# Generated by Django 3.1.3 on 2021-01-09 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_userdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='full_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='location',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
